# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0aedd8d21e736e57b3260655799038f5a7f0c846d200b39e59f04af1bcb05b2250a73fee32fe5cd7938b8abb4170cb7c58ce0322522204da946daf3ffbddbe4

test:
  secret_key_base: 48043bef00e812929340d9ba7b9739ea7eb802840ddd83f890c137a49996fc70496c9877227b583a4d82ef50e339095693eb580894533db18008908871855143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
